### ISSUE TITLE
Crash when initializing game

### ISSUE THREAD

**Issue by Karashok-Leo** [flowerinsnowdh/GreatScrollableTooltips#9] opened 2024-03-07 14:44 UTC
https://pastebin.com/msEVCnpH
mc version 1.20.1 fabric
mod version 13.0.4

**Comment by flowerinsnowdh** [comment] 2024-03-14 17:55
您好！感谢您的反馈！

首先，让我先予以致歉，前几天我因为感冒发烧，包括至今还没有痊愈，没有顾及相关 issues，让您久等了

但是非常遗憾，我在测试该 Mod 位于 1.20.1-fabric 版本时并没有出现在初始化时或运行时游戏崩溃的问题

我发现您安装了许多 Mod，我猜测可能是由于 Mod 冲突导致的游戏崩溃

但我安装了日志中同样报告 Mixin 错误的相同版本的 Mod [architectury](https://github.com/architectury/architectury)，我的游戏依然运行正常，没有发生崩溃

所以从现有的情报中，我没有找到问题在哪里，如果您愿意将该 Mod Pack 分享给我，我或许可以进一步查找错误原因

感谢您的支持！

<hr />

*Hello! Thanks for your feedback!*

*First of all, let me apologize. I didn’t take care of related issues because I had a cold and fever a few days ago, including that he has not recovered yet, so I kept you waiting for so long.*

*But unfortunately, when I tested the Mod in version 1.20.1-fabric, there was no problem of the game crashing during initialization or runtime.*

*I noticed that you have a lot of mods installed, I guess the game may be crashing due to mod conflicts.*

*But I installed the same version of Mod [architectury](https://github.com/architectury/architectury) that also reported the Mixin error in the log, and my game still ran normally without crashing.*

*So from the existing information, I have not found where the problem is. If you are willing to share the Mod Pack with me, I may be able to further find out the cause of the error.*

*Thank you for your support!*

**Comment by Karashok-Leo** [comment] 2024-03-15 11:52
怎么发给你

<hr />

*How to send it to you*

**Comment by flowerinsnowdh** [comment] 2024-03-15 23:14
这是我的QQ：3184823291

这是我的Email：flowerimsnow@gmail.com

可以选择一个方式发送给我，然后在此留言

<hr />

*This is my QQ: 3184823291*

*This is my email: flowerimsnow@gmail.com*

*You can choose a way to send it to me, and then leave a comment here*

**Comment by flowerinsnowdh** [comment] 2024-03-15 23:23
> 怎么发给你
> 
> _How to send it to you_

这是我的QQ：3184823291

这是我的Email：[flowerimsnow@gmail.com](mailto:flowerimsnow@gmail.com)

可以选择一个方式发送给我，然后在此留言

<hr />

*This is my QQ: 3184823291*

*This is my email: [flowerimsnow@gmail.com](mailto:flowerimsnow@gmail.com)*

*You can choose a way to send it to me, and then leave a comment here*

**Comment by flowerinsnowdh** [comment] 2024-03-16 03:53
已经可以确定是 [https://github.com/architectury/architectury-api](architectury-api) 与本 Mod 的 Mixin 冲突导致该 Mod 崩溃，已于 https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/pull/11 修复，并即将在功能完善后发布修复版本，再次感谢您的反馈

<hr />

*It has been determined that [https://github.com/architectury/architectury-api](architecture-api) conflicts with the Mixin of this Mod, causing the Mod to crash. This has been fixed at https://github.com/flowerinsnow-lights-opensource /GreatScrollableTooltips/pull/11, and a fixed version will be released soon after the feature is improvement. Thank you again for your feedback.*

**Comment by flowerinsnowdh** [comment] 2024-03-16 03:53
已经可以确定是 [https://github.com/architectury/architectury-api](architectury-api) 与本 Mod 的 Mixin 冲突导致该 Mod 崩溃，已于 https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/pull/11 修复，并即将在功能完善后发布修复版本，再次感谢您的反馈

更多版本的修复需要一段时间

<hr />

*It has been determined that [https://github.com/architectury/architectury-api](architecture-api) conflicts with the Mixin of this Mod, causing the Mod to crash. This has been fixed at https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/pull/11, and a fixed version will be released soon after the feature is improvement. Thank you again for your feedback.*

*Fixes for more versions will take some time*

**Closed as completed** 2024-03-18 19:44 UTC
Labels: bug
