### ISSUE TITLE
Crash on clicking Options in the esc menu

### ISSUE THREAD

**Issue by lastedito** [flowerinsnowdh/GreatScrollableTooltips#65] opened 2024-08-04 17:12 UTC
forge 1.20.1
modpack: craft to exile 2 (0.6.2)
crash report: 
[crash-2024-08-04_19.04.19-client.txt](https://github.com/user-attachments/files/16488363/crash-2024-08-04_19.04.19-client.txt)
If you need anything else, let me know

edit: forgot to add labels, my bad

**Comment by flowerinsnowdh** [comment] 2024-08-06 12:26
Thank you.

Fixed on v15.1.2+forge

**Comment by lastedito** [comment] 2024-08-06 18:10
Hey, thank you for the fix.
There's another problem now, I updated forge version to the version you upgraded the mod at in case but couldn't find what FNML was ^^ Please help me out :d
![image](https://github.com/user-attachments/assets/dd5787fd-f384-4337-9e08-6350739d0a25)
[crash-2024-08-06_20.08.17-fml.txt](https://github.com/user-attachments/files/16514192/crash-2024-08-06_20.08.17-fml.txt)

edit: Since the issue is closed, idk if you'll notice it so I might make another one that reference this issue in a few days
edit: edit: Okay uhm weird stuffs, after I upgraded forge to 47.3.5, the version before the fix now works with no crash when entering options.

**Comment by flowerinsnowdh** [comment] 2024-08-06 19:19
> Hey, thank you for the fix. There's another problem now, I updated forge version to the version you upgraded the mod at in case but couldn't find what FNML was ^^ Please help me out :d ![image](https://private-user-images.githubusercontent.com/11960432/355556273-dd5787fd-f384-4337-9e08-6350739d0a25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzE5ODEsIm5iZiI6MTcyMjk3MTY4MSwicGF0aCI6Ii8xMTk2MDQzMi8zNTU1NTYyNzMtZGQ1Nzg3ZmQtZjM4NC00MzM3LTllMDgtNjM1MDczOWQwYTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE5MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMGJmN2ZkMDNiN2NhY2Q1YjZmZmQyNGQzMzJlZDQ0NmQ3ZTgyMTcyNTlkMmQzYmJkYTJlNGIyZjllNTUwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iS4sSJoqHYPcNyj-u28n6gsHmHaBJvsWSF77KhUb6Nk) [crash-2024-08-06_20.08.17-fml.txt](https://github.com/user-attachments/files/16514192/crash-2024-08-06_20.08.17-fml.txt)
> 
> edit: Since the issue is closed, idk if you'll notice it so I might make another one that reference this issue in a few days edit: edit: Okay uhm weird stuffs, after I upgraded forge to 47.3.5, the version before the fix now works with no crash when entering options.

Hello, this problem caused by your configuration file has bad syntax. Please paste your `config/great_scrollable_tootlips.conf` here and I will check the error.

**Comment by polykatt** [comment] 2024-08-07 02:41
Hi, I have this same crash on forge version 47.3.0.
This is what the config file looks like:

enable 'true'
sensitivity '5'

**Comment by flowerinsnowdh** [comment] 2024-08-07 21:34
> Hi, I have this same crash on forge version 47.3.0. This is what the config file looks like:
> 
> enable 'true' sensitivity '5'

This is so weird. this configuration has no problem. And there's no crashes for me.

Could you please try deleting the configuration file and try again?

**Comment by polykatt** [comment] 2024-08-09 04:36
okay, a fresh install worked everything is fine now. thank you

**Closed as completed** 2024-08-09 06:21 UTC
Labels: crash
